"""empty message

Revision ID: d44c0aa7bbd4
Revises: 6215fa4fdf7f
Create Date: 2021-01-03 16:23:33.020092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44c0aa7bbd4'
down_revision = '6215fa4fdf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_timings', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_timings')
    # ### end Alembic commands ###
